--CREATE OR REPLACE VIEW V_MOVES_MANAGEMENT AS
WITH
CURRENT_CALENDAR AS(
SELECT
  CC.*
FROM RPT_PBH634.V_CURRENT_CALENDAR CC
)

,KSM_STAFF AS (
SELECT
 *
FROM RPT_PBH634.V_FRONTLINE_KSM_STAFF
WHERE FORMER_STAFF IS NULL
  AND TEAM IN ('AF', 'MG')
)

,ACTIVE_PROSPECT AS (
  SELECT
    P.PROSPECT_ID
    ,PE.ID_NUMBER
    ,P.STAGE_CODE
  FROM PROSPECT P
  INNER JOIN PROSPECT_ENTITY PE
  ON P.PROSPECT_ID = PE.PROSPECT_ID
    AND P.ACTIVE_IND = 'Y'
    AND PE.PRIMARY_IND = 'Y'
)

,PROSPECTS AS (
--,MGO_LGO AS(
SELECT DISTINCT
  AP.PROSPECT_ID
  ,AP.STAGE_CODE
  ,AH.id_number
  ,AH.ASSIGNMENT_ID_NUMBER
  ,AH.assignment_report_name
  ,TRIM(AH.assignment_type_desc) AS assignment_type_desc
  ,KST.TEAM
FROM RPT_PBH634.V_ASSIGNMENT_HISTORY AH
INNER JOIN KSM_STAFF KST
ON AH.assignment_id_number = KST.ID_NUMBER
LEFT JOIN ACTIVE_PROSPECT AP
ON AH.id_number = AP.ID_NUMBER
WHERE AH.assignment_active_ind = 'Y'
  AND AH.assignment_type IN ('PM', 'LG')
  AND AH.primary_ind = 'Y'
UNION ALL
--,OUTREACH_TASK AS (
SELECT DISTINCT
  AP.prospect_id
  ,AP.STAGE_CODE
  ,TR.id_number
  ,TR.task_responsible_id AS ASSIGNMENT_ID_NUMBER
  ,TR.task_responsible AS assignment_report_name
  ,'Outreach Task' AS assignment_type_desc
  ,KST.TEAM
FROM RPT_DGZ654.V_TASK_REPORT TR
INNER JOIN KSM_STAFF KST
ON TR.task_responsible_id = KST.ID_NUMBER
LEFT JOIN ACTIVE_PROSPECT AP
ON TR.id_number = AP.ID_NUMBER
WHERE TR.task_code = 'CO'
  AND TR.SCHED_DATE > rpt_pbh634.ksm_pkg_tmp.to_date2('12/31/2020','MM-DD-YY')
  AND TR.task_status_code = '2'
UNION ALL
--VISIT_OUTREACH AS (
SELECT DISTINCT
  AP.PROSPECT_ID
  ,AP.STAGE_CODE
  ,T.id_number
  ,T.task_responsible_id AS ASSIGNMENT_ID_NUMBER
  ,T.task_responsible AS assignment_report_name
  ,'Visit Task' AS assignment_type_desc
  ,KST.TEAM
FROM RPT_PBH634.V_KSM_TASKS T
INNER JOIN KSM_STAFF KST
ON T.task_responsible_id = KST.ID_NUMBER
LEFT JOIN ACTIVE_PROSPECT AP
ON T.id_number = AP.ID_NUMBER
WHERE T.task_code = 'V'
  AND T.SCHED_DATE > rpt_pbh634.ksm_pkg_tmp.to_date2('12/31/2020','MM-DD-YY')
  AND T.task_status_code = '2'
UNION ALL
--Active Proposal Manager
SELECT DISTINCT
 PHF.PROSPECT_ID
 ,AP.STAGE_CODE
 ,AP.ID_NUMBER
 ,PHF.proposal_manager_id AS ASSIGNMENT_ID_NUMBER
 ,PHF.proposal_manager AS assignment_report_name
 ,'Active Proposal Manager' AS assignment_type_desc
 ,KST.TEAM
FROM RPT_PBH634.V_PROPOSAL_HISTORY_FAST PHF
INNER JOIN KSM_STAFF KST
ON PHF.proposal_manager_id = KST.ID_NUMBER
LEFT JOIN ACTIVE_PROSPECT AP
ON PHF.prospect_id = AP.PROSPECT_ID
WHERE PHF.proposal_active = 'Y'
UNION ALL
--Active Proposal Assist
SELECT DISTINCT
 PHF.PROSPECT_ID
 ,AP.STAGE_CODE
 ,AP.ID_NUMBER
 ,PHF.proposal_assist_id AS ASSIGNMENT_ID_NUMBER
 ,PHF.proposal_assist AS assignment_report_name
 ,'Active Proposal Assist' AS assignment_type_desc
 ,KST.TEAM
FROM RPT_PBH634.V_PROPOSAL_HISTORY_FAST PHF
INNER JOIN KSM_STAFF KST
ON PHF.proposal_assist_id = KST.ID_NUMBER
LEFT JOIN ACTIVE_PROSPECT AP
ON PHF.prospect_id = AP.PROSPECT_ID
WHERE PHF.proposal_active = 'Y'
UNION ALL
--Visits
SELECT DISTINCT
  AP.PROSPECT_ID
  ,AP.STAGE_CODE
  ,CR.id_number
  ,CR.credited AS ASSIGNMENT_ID_NUMBER
  ,CR.credited_name AS assignment_report_name
  ,'Visit in Last Yr' AS assignment_type_desc
  ,KST.TEAM
FROM RPT_PBH634.V_CONTACT_REPORTS_FAST CR
INNER JOIN KSM_STAFF KST
ON CR.credited = KST.ID_NUMBER
LEFT JOIN ACTIVE_PROSPECT AP
ON CR.id_number = AP.ID_NUMBER
CROSS JOIN CURRENT_CALENDAR CC
WHERE CONTACT_TYPE_CODE = 'V'
  AND CONTACT_DATE BETWEEN CC.TODAY-365 and CC.TODAY
UNION ALL
--Contacted
SELECT DISTINCT
  AP.PROSPECT_ID
  ,AP.STAGE_CODE
  ,CR.id_number
  ,CR.credited AS ASSIGNMENT_ID_NUMBER
  ,CR.credited_name AS assignment_report_name
  ,'Contact in Last Yr' AS assignment_type_desc
  ,KST.TEAM
FROM RPT_PBH634.V_CONTACT_REPORTS_FAST CR
INNER JOIN KSM_STAFF KST
ON CR.credited = KST.ID_NUMBER
LEFT JOIN ACTIVE_PROSPECT AP
ON CR.id_number = AP.ID_NUMBER
CROSS JOIN CURRENT_CALENDAR CC
WHERE CONTACT_TYPE_CODE <> 'V'
  AND CONTACT_DATE BETWEEN CC.TODAY-365 and CC.TODAY
)

,CONCAT_ASSIGNMENTS AS (
SELECT
  ID_NUMBER
  ,LISTAGG(ASSIGNMENT_TYPE_DESC, '; ') WITHIN GROUP (ORDER BY ASSIGNMENT_REPORT_NAME) "ASSIGNMENT_TYPE_DESC"
  ,LISTAGG(ASSIGNMENT_REPORT_NAME, '; ') WITHIN GROUP (ORDER BY ASSIGNMENT_REPORT_NAME) "ASSIGNMENT_REPORT_NAME"
FROM PROSPECTS
GROUP BY ID_NUMBER
ORDER BY ID_NUMBER
)

,DISTINCT_ASSIGNMENT AS (
  SELECT DISTINCT
    ID_NUMBER
    ,ASSIGNMENT_ID_NUMBER
    ,ASSIGNMENT_REPORT_NAME
  --  ,assignment_type_desc
  FROM PROSPECTS
)

,DISTINCT_ASSIGN_TYPE AS (
  SELECT DISTINCT
    ID_NUMBER
    ,ASSIGNMENT_ID_NUMBER
    ,assignment_type_desc
  FROM PROSPECTS
)

,DISTINCT_CONCAT AS (
  SELECT
    ID_NUMBER
    ,ASSIGNMENT_ID_NUMBER
    ,LISTAGG(ASSIGNMENT_REPORT_NAME, '; ') WITHIN GROUP (ORDER BY ASSIGNMENT_REPORT_NAME) "DEDUPED_ASSIGN_NAME"
  FROM DISTINCT_ASSIGNMENT
  GROUP BY ID_NUMBER, ASSIGNMENT_ID_NUMBER, ASSIGNMENT_REPORT_NAME
  ORDER BY ID_NUMBER
)

,DISTINCT_TYPE AS (
    SELECT
    ID_NUMBER
    ,ASSIGNMENT_ID_NUMBER
    ,LISTAGG(ASSIGNMENT_TYPE_DESC, '; ') WITHIN GROUP (ORDER BY ASSIGNMENT_ID_NUMBER) "DEDUPED_ASSIGN_TYPE"
  FROM DISTINCT_ASSIGN_TYPE
  GROUP BY ID_NUMBER, ASSIGNMENT_ID_NUMBER
  ORDER BY ID_NUMBER
)

,DEDUPED_STUFF AS (
   SELECT
     DC.ID_NUMBER
     ,DC.DEDUPED_ASSIGN_NAME
     ,DT."DEDUPED_ASSIGN_TYPE"
   FROM DISTINCT_CONCAT DC
   INNER JOIN DISTINCT_TYPE DT
   ON DC.ID_NUMBER = DT.ID_NUMBER
     AND DC.ASSIGNMENT_ID_NUMBER = DT.ASSIGNMENT_ID_NUMBER
)

,ASSIGNMENTS AS (
  SELECT
   AH.ID_NUMBER
   ,AH.assignment_id_number
   ,AH.ASSIGNMENT_TYPE_DESC
   ,AH.ASSIGNMENT_REPORT_NAME
   FROM RPT_PBH634.V_ASSIGNMENT_HISTORY AH
   INNER JOIN KSM_STAFF KST
   ON AH.assignment_id_number = KST.ID_NUMBER
    WHERE ASSIGNMENT_TYPE IN ('PM', 'LG')
      AND ASSIGNMENT_ACTIVE_IND = 'Y'
)

,LAST_KSM_GIFT AS (
    SELECT
     KGS."ID_NUMBER"
     ,KGS."LAST_GIFT_DATE"
     ,KGS."NGC_LIFETIME"
     ,KGS."AF_CFY"
     ,KGS."AF_PFY1"
    FROM PROSPECTS P
    INNER JOIN RPT_PBH634.V_KSM_GIVING_SUMMARY KGS
    ON P.ID_NUMBER = KGS.ID_NUMBER
)

,PLEDGE_DATA AS (
    SELECT DISTINCT
      PD.ID_NUMBER
      ,MIN(PD.NEXT_PAYMENT_DATE) AS NEXT_PAYMENT_DATE
    FROM PROSPECTS P
    INNER JOIN RPT_ABM1914.V_PLEDGE_DATA PD
    ON P.ID_NUMBER = PD.ID_NUMBER
    CROSS JOIN CURRENT_CALENDAR CC
    WHERE PD.NEXT_PAYMENT_DATE BETWEEN CC.CURR_FY_START AND CC.NEXT_FY_START
      AND PD.PLEDGE_STATUS = 'Active'
    GROUP BY PD.ID_NUMBER
)

,CONTACT_INFO AS (
  SELECT
    P.ID_NUMBER
    ,CRF.CONTACT_DATE
    ,CRF.contact_type
    ,CRF.CREDITED
    ,CRF.credited_name
  FROM PROSPECTS P
  INNER JOIN RPT_PBH634.V_CONTACT_REPORTS_FAST CRF
  ON P.ID_NUMBER = CRF.id_number
  INNER JOIN KSM_STAFF KST
  ON CRF.credited = KST.ID_NUMBER
  UNION
  SELECT
    P.ID_NUMBER
    ,CRF.CONTACT_DATE
    ,CRF.contact_type
    ,CRF.CREDITED
    ,CRF.credited_name
  FROM PROSPECTS P
  INNER JOIN RPT_PBH634.V_CONTACT_REPORTS_FAST CRF
  ON P.ID_NUMBER = CRF.id_number
  WHERE CRF.credited = '0000804796'
)

,LAST_CONTACT AS (
  SELECT
    CI.ID_NUMBER
    ,min(CI.contact_date) KEEP(dense_rank FIRST ORDER BY CI.CONTACT_DATE DESC, CI.CREDITED_NAME ASC)
       AS contact_date
    ,min(CI.CONTACT_TYPE) KEEP(dense_rank FIRST ORDER BY CI.CONTACT_DATE DESC, CI.CREDITED_NAME ASC)
      AS CONTACT_TYPE
    ,MIN(CI.CREDITED_NAME) KEEP(dense_rank FIRST ORDER BY CI.CONTACT_DATE DESC, CI.CREDITED_NAME ASC)
      AS CREDITED_NAME
  FROM CONTACT_INFO CI
  CROSS JOIN CURRENT_CALENDAR CC
  INNER JOIN KSM_STAFF KST
  ON CI.credited = KST.ID_NUMBER
 -- WHERE CI.contact_date BETWEEN CC.TODAY-90 AND CC.TODAY
  GROUP BY CI.ID_NUMBER
)

,UPCOMING_PROP AS (
   SELECT DISTINCT
     PHF.PROSPECT_ID
     ,CASE WHEN PHF.ASK_DATE BETWEEN CC.TODAY AND CC.TODAY+30 THEN 'Y' ELSE 'N' END AS "UPCOMING_ASK_DATE"
     ,CASE WHEN PHF.ASK_DATE BETWEEN CC.TODAY AND CC.TODAY+30 THEN PHF.ASK_DATE ELSE NULL END AS "ASK_DATE"
     ,CASE WHEN PHF.CLOSE_DATE BETWEEN CC.TODAY AND CC.TODAY+30 THEN 'Y' ELSE 'N' END AS "UPCOMING_CLOSE_DATE"
     ,CASE WHEN PHF.CLOSE_DATE BETWEEN CC.TODAY AND CC.TODAY+30 THEN PHF.CLOSE_DATE ELSE NULL END AS "CLOSE_DATE"
     ,CASE WHEN PHF.ask_date < CC.TODAY AND PHF.proposal_status = 'Anticipated' THEN 'Y' ELSE 'N' END AS "ASK_DATE_PASSED"
     ,CASE WHEN PHF.ask_date < CC.TODAY AND PHF.proposal_status = 'Anticipated' THEN PHF.ask_date END AS "PASSED_DATE"
     ,CASE WHEN PHF.proposal_manager_id = KST.ID_NUMBER  THEN 'Y' ELSE 'N' END AS "PROPOSAL_MANAGER_KSM_STAFF"
     ,PHF.proposal_manager
     ,PHF.proposal_active
   FROM RPT_PBH634.V_PROPOSAL_HISTORY_FAST PHF
   CROSS JOIN CURRENT_CALENDAR CC
   INNER JOIN PROSPECTS P
   ON PHF.PROSPECT_ID = P.PROSPECT_ID
   LEFT JOIN KSM_STAFF KST
   ON PHF.proposal_manager_id = KST.ID_NUMBER
  -- WHERE (PHF.ask_date BETWEEN CC.TODAY AND CC.TODAY+30) OR (PHF.close_date BETWEEN CC.TODAY AND CC.TODAY+30)
      WHERE PHF.proposal_active = 'Y'
      AND PHF.ksm_proposal_ind = 'Y'
)

,RECENT_PR AS (
  SELECT
    P.ID_NUMBER
    ,NP.EVALUATION_DATE
    ,NP.EVALUATION_RATING AS RESEARCH_EVALUATION
    ,NP.GIVING_TOTAL AS NU_LIFETIME_GIVING
  FROM Nu_Prs_Trp_Prospect NP
  INNER JOIN PROSPECTS P
  ON NP.ID_NUMBER = P.ID_NUMBER

)

,RECENT_NEWS AS (
   SELECT
     N.ID_NUMBER
     ,MIN(N.NOTE_DATE) KEEP(DENSE_RANK FIRST ORDER BY N.NOTE_DATE DESC, N.DESCRIPTION ASC) AS NOTE_DATE
     ,MIN(N.DESCRIPTION) KEEP(DENSE_RANK FIRST ORDER BY N.NOTE_DATE DESC, N.DESCRIPTION ASC) AS "DESCRIPTION"
   FROM NOTES N
   CROSS JOIN CURRENT_CALENDAR CC
   INNER JOIN PROSPECTS P
   ON N.ID_NUMBER = P.ID_NUMBER
   WHERE N.NOTE_TYPE = 'NE' AND N.AUTHOR_ID_NUMBER = '0000605801'
     AND N.NOTE_DATE BETWEEN CC.TODAY-14 AND CC.TODAY
   GROUP BY N.ID_NUMBER
)

,LAST_CONTACT_DEAN AS (
  SELECT
    CI.ID_NUMBER
    ,min(CI.contact_date) KEEP(dense_rank FIRST ORDER BY CI.CONTACT_DATE DESC, CI.CREDITED_NAME ASC)
       AS contact_date
    ,min(CI.CONTACT_TYPE) KEEP(dense_rank FIRST ORDER BY CI.CONTACT_DATE DESC, CI.CREDITED_NAME ASC)
      AS CONTACT_TYPE
    ,MIN(CI.CREDITED_NAME) KEEP(dense_rank FIRST ORDER BY CI.CONTACT_DATE DESC, CI.CREDITED_NAME ASC)
      AS CREDITED_NAME
  FROM CONTACT_INFO CI
  CROSS JOIN CURRENT_CALENDAR CC
  WHERE CI.CREDITED = '0000804796'
  GROUP BY CI.ID_NUMBER
)

,Attended_Reunion AS (
  SELECT DISTINCT
   EP.id_number
   FROM EP_EVENT EE
   LEFT JOIN EP_PARTICIPANT EP
   ON EE.EVENT_ID = EP.EVENT_ID
   INNER JOIN PROSPECTS P
   ON EP.ID_NUMBER = P.ID_NUMBER
  WHERE EE.EVENT_NAME LIKE '%KSM%' AND EE.EVENT_NAME LIKE '%Reunion%'
      AND EE.EVENT_TYPE = '02'
)

,LAST_EVENT AS (
  SELECT
   PF.ID_NUMBER
   ,min(PF.START_DT) KEEP(dense_rank FIRST ORDER BY PF.START_DT DESC, PF.EVENT_NAME ASC) AS START_DT
   ,MIN(PF.EVENT_NAME) KEEP(dense_rank FIRST ORDER BY PF.START_DT DESC, PF.EVENT_NAME ASC) AS EVENT_NAME
   FROM rpt_pbh634.v_nu_event_participants_fast PF
   INNER JOIN PROSPECTS P
   ON PF.id_number = P.ID_NUMBER
   WHERE PF.ksm_event = 'Y'
   GROUP BY PF.ID_NUMBER
)

,committee_info AS (
   SELECT DISTINCT
     c.id_number
     ,listagg(ct.full_desc, chr(13)) Within Group (order by ct.full_desc) as committees
    FROM committee c
    INNER JOIN tms_committee_table ct
    ON c.committee_code = ct.committee_code
    WHERE c.committee_status_code = 'C'
    GROUP BY c.id_number
)

,KELLOGG_SPEAKER AS(
  SELECT
    A.ID_NUMBER
    ,MIN(rpt_pbh634.ksm_pkg_tmp.to_date2(A.START_DT, 'YYYYMMDD')) KEEP(dense_rank FIRST ORDER BY A.START_DT DESC, A.XCOMMENT ASC) AS START_DT
    ,MIN(A.XCOMMENT) KEEP (dense_rank FIRST ORDER BY A.START_DT DESC, A.XCOMMENT ASC) AS XCOMMENT
  FROM ACTIVITY A
  INNER JOIN PROSPECTS P
  ON A.ID_NUMBER = P.ID_NUMBER
  WHERE A.ACTIVITY_CODE = 'KSP'
  GROUP BY A.ID_NUMBER
)

,LAST_VISIT AS (
  SELECT
    CI.ID_NUMBER
    ,min(CI.contact_date) KEEP(dense_rank FIRST ORDER BY CI.CONTACT_DATE DESC, CI.CREDITED_NAME ASC)
       AS contact_date
    ,min(CI.CONTACT_TYPE) KEEP(dense_rank FIRST ORDER BY CI.CONTACT_DATE DESC, CI.CREDITED_NAME ASC)
      AS CONTACT_TYPE
    ,MIN(CI.CREDITED_NAME) KEEP(dense_rank FIRST ORDER BY CI.CONTACT_DATE DESC, CI.CREDITED_NAME ASC)
      AS CREDITED_NAME
  FROM CONTACT_INFO CI
  CROSS JOIN CURRENT_CALENDAR CC
  INNER JOIN KSM_STAFF KST
  ON CI.credited = KST.ID_NUMBER
  WHERE CI.CONTACT_TYPE = 'Visit'
  GROUP BY CI.ID_NUMBER
)

SELECT DISTINCT
  E.ID_NUMBER
  ,P.PROSPECT_ID
  ,E.REPORT_NAME
  ,E.PREF_NAME_SORT
  ,E.PREF_MAIL_NAME
  ,rpt_pbh634.ksm_pkg_tmp.to_date2(E.BIRTH_DT, 'YYYY-MM-DD') AS BIRTH_DT
  ,rpt_pbh634.ksm_pkg_tmp.to_date2(E.SPOUSE_BIRTH_DT, 'YYYY-MM-DD') AS SPOUSE_BIRTH_DT
  ,EKD."FIRST_MASTERS_YEAR"
  ,LKG."LAST_GIFT_DATE"
  ,PD.NEXT_PAYMENT_DATE AS NEXT_PLEDGE_PAYMENT_DATE
 ,CASE WHEN LC.ID_NUMBER IS NOT NULL THEN 'Y' ELSE ' ' END AS "CONTACT_LAST_90_DAYS"
 ,LC.CONTACT_DATE
  ,LC.CREDITED_NAME
 ,UP.UPCOMING_ASK_DATE
  ,UP.ASK_DATE
  ,UP.UPCOMING_CLOSE_DATE
  ,UP.CLOSE_DATE
  ,UP.ASK_DATE_PASSED
  ,UP.PASSED_DATE
  ,UP.PROPOSAL_ACTIVE
  ,UP."PROPOSAL_MANAGER_KSM_STAFF"
  ,CASE WHEN EMP.DATE_MODIFIED BETWEEN CC.TODAY-30 AND CC.TODAY THEN 'Y' ELSE 'N' END AS "UPDATED_EMPLOYER_INFO"
,RPR.EVALUATION_DATE
  ,RPR.RESEARCH_EVALUATION AS EVALUATION_RATING
 ,RN.NOTE_DATE AS RECENT_NEWS_DATE
  ,RN.DESCRIPTION AS NEWS_DESCRIPTION
 ,LCD.CONTACT_DATE AS LAST_CONTACT_DEAN
  ,LCD.CONTACT_TYPE AS CONTACT_TYPE_DEAN
 ,CASE WHEN AR.ID_NUMBER IS NOT NULL THEN 'Y' ELSE ' ' END AS "PAST_REUNION_ATTEND"
  ,LE.START_DT AS LAST_EVENT_DATE
  ,LE.EVENT_NAME
 ,CI.COMMITTEES
  ,KSP.START_DT AS SPEAKER_DT
  ,KSP.XCOMMENT AS SPEAKER_COMMENT
  ,LV.CONTACT_DATE AS LAST_VISIT_DATE
  ,LV.CREDITED_NAME AS LAST_VISIT_CREDITED
  ,A.assignment_report_name AS MANAGER
  ,A.assignment_type_desc
  ,TS.short_desc AS PROSPECT_STAGE
  ,MG.pr_segment
  ,MG.pr_score
  ,EKH."HOUSEHOLD_CITY"
  ,EKH."HOUSEHOLD_STATE"
  ,EKH."HOUSEHOLD_ZIP"
  ,EKH."HOUSEHOLD_COUNTRY"
 ,EMP.JOB_TITLE AS PRIMARY_EMPLOYMENT_JOB_TITLE
  ,CASE WHEN EMP.EMPLOYER_ID_NUMBER = ' ' THEN EMP.EMPLOYER_NAME1 ELSE EEMP.REPORT_NAME END AS PRIMARY_EMPLOYER_NAME
  --,PR.NU_LIFETIME_GIVING
  ,LKG."NGC_LIFETIME" AS KELLOGG_LIFETIME_GIVING
  ,KGC."CAMPAIGN_GIVING"
  ,LKG."AF_CFY"
  ,LKG."AF_PFY1"
  ,KLC.KLC_lev_cfy
  ,P.ASSiGNMENT_TYPE_DESC AS PROSPECT_ASSIGN_TYPE
  ,P.assignment_report_name
  ,CA.ASSIGNMENT_TYPE_DESC AS PROSPECT_ASSIGN_TYPE
  ,CA.ASSIGNMENT_REPORT_NAME
  ,DS."DEDUPED_ASSIGN_NAME"
  ,DS."DEDUPED_ASSIGN_TYPE"
  ,CC."TODAY",CC."YESTERDAY",CC."YESTERDAY_LAST_YEAR",CC."NINETY_DAYS_AGO"
  ,CC."CURR_FY",CC."PREV_FY_START",CC."CURR_FY_START",CC."NEXT_FY_START",CC."CURR_PY"
  ,CC."PREV_PY_START",CC."CURR_PY_START",CC."NEXT_PY_START",CC."PREV_FY_TODAY",CC."NEXT_FY_TODAY"
  ,CC."PREV_WEEK_START",CC."CURR_WEEK_START",CC."NEXT_WEEK_START",CC."PREV_MONTH_START",CC."CURR_MONTH_START",CC."NEXT_MONTH_START"
FROM ENTITY E
CROSS JOIN CURRENT_CALENDAR CC
INNER JOIN PROSPECTS P
ON E.ID_NUMBER = P.ID_NUMBER
LEFT JOIN CONCAT_ASSIGNMENTS CA
ON P.ID_NUMBER = CA.ID_NUMBER
LEFT JOIN DEDUPED_STUFF DS
ON P.ID_NUMBER = DS.ID_NUMBER
LEFT JOIN RPT_PBH634.V_ENTITY_KSM_DEGREES EKD
ON P.ID_NUMBER = EKD."ID_NUMBER"
LEFT JOIN LAST_KSM_GIFT LKG
ON P.ID_NUMBER = LKG.ID_NUMBER
LEFT JOIN PLEDGE_DATA PD
ON P.ID_NUMBER = PD.ID_NUMBER
LEFT JOIN LAST_CONTACT LC
ON P.ID_NUMBER = LC.ID_NUMBER
LEFT JOIN UPCOMING_PROP UP
ON P.PROSPECT_ID = UP.PROSPECT_ID
LEFT JOIN EMPLOYMENT EMP
ON P.ID_NUMBER = EMP.ID_NUMBER
  AND EMP.JOB_STATUS_CODE = 'C'
  AND EMP.PRIMARY_EMP_IND = 'Y'
LEFT JOIN ENTITY EEMP
ON EMP.EMPLOYER_ID_NUMBER = EEMP.ID_NUMBER
LEFT JOIN RECENT_PR RPR
ON P.ID_NUMBER = RPR.ID_NUMBER
LEFT JOIN RECENT_NEWS RN
ON P.ID_NUMBER = RN.ID_NUMBER
LEFT JOIN LAST_CONTACT_DEAN LCD
ON P.ID_NUMBER = LCD.ID_NUMBER
LEFT JOIN ATTENDED_REUNION AR
ON P.ID_NUMBER = AR.ID_NUMBER
LEFT JOIN LAST_EVENT LE
ON P.ID_NUMBER = LE.ID_NUMBER
LEFT JOIN COMMITTEE_INFO CI
ON P.ID_NUMBER = CI.ID_NUMBER
LEFT JOIN KELLOGG_SPEAKER KSP
ON P.ID_NUMBER = KSP.ID_NUMBER
LEFT JOIN LAST_VISIT LV
ON P.ID_NUMBER = LV.ID_NUMBER
LEFT JOIN ASSIGNMENTS A
ON P.ID_NUMBER = A.ID_NUMBER
LEFT JOIN TMS_STAGE TS
ON P.STAGE_CODE = TS.stage_code
LEFT JOIN RPT_PBH634.V_KSM_MODEL_MG MG
ON P.ID_NUMBER = MG.id_number
LEFT JOIN RPT_PBH634.V_ENTITY_KSM_HOUSEHOLDS EKH
ON P.ID_NUMBER = EKH."ID_NUMBER"
LEFT JOIN RPT_PBH634.V_KSM_GIVING_CAMPAIGN KGC
ON P.ID_NUMBER = KGC."ID_NUMBER"
LEFT JOIN RPT_ABM1914.V_KLC_MEMBERS klc
ON P.ID_NUMBER = KLC."ID_NUMBER"
;
