CREATE OR REPLACE VIEW TABLEAU_STEWARDSHIP_DAILY_GIFT_LOG AS
With

dts As (
--  Select prev_month_start As dt1, yesterday As dt2, curr_fy
  /* Alternate date ranges for debugging */
  Select
    cal.prev_fy_start-365 As dt1
    , yesterday As dt2
    , curr_fy
  From TABLE(KSM_PKG_CALENDAR.tbl_current_calendar) cal
)

,KSM_DEG AS (
  SELECT
   DONOR_ID
   ,DEGREES_CONCAT
   ,LAST_NONCERT_YEAR
   ,PROGRAM_GROUP
  FROM MV_ENTITY_KSM_DEGREES
)

, ksm_cu As (
  Select
    LEGACY_ALLOCATION_CODE
    ,DESIGNATION_STATUS
    ,DESIGNATION_NAME
    ,KSM_AF_FLAG
  From MV_KSM_DESIGNATION
  WHERE KSM_CRU_FLAG = 'Y'
)

/*GAB*/
,GAB AS(
  SELECT
    CONSTITUENT_DONOR_ID AS ID_NUMBER
    ,trim(involvement_status || ' ' || involvement_role) AS gab_role
  FROM V_COMMITTEE_GAB
  WHERE INVOLVEMENT_ROLE NOT LIKE '%Life%'
)

--GAB INDICATOR...USE NU_GFT_TRP, can I use MV_KSM_TRANS? doesn't seem to be used further down

/*KAC*/
,KAC AS (
  SELECT
    CONSTITUENT_DONOR_ID AS ID_NUMBER
    ,trim(involvement_status || ' ' || involvement_role) AS kac_role
  FROM V_COMMITTEE_KAC
)
/*TRUSTEE*/
,TRUSTEE AS (
  SELECT
    CONSTITUENT_DONOR_ID AS ID_NUMBER
    ,trim(involvement_status || ' ' || involvement_role) AS trustee_role
  FROM V_COMMITTEE_TRUSTEE
)
/*KEBA*/
,KEBA AS (
  SELECT
    CONSTITUENT_DONOR_ID AS ID_NUMBER
    ,trim(involvement_status || ' ' || involvement_role) AS keba_role
  FROM V_COMMITTEE_ASIA
)
/*BOARDS*/
,BOARDS AS (
  SELECT
    CONSTITUENT_DONOR_ID AS ID_NUMBER
    ,LISTAGG(INVOLVEMENT_NAME, ', ') WITHIN GROUP (ORDER BY INVOLVEMENT_NAME) AS COMMITTEES
  FROM MV_INVOLVEMENT
  WHERE INVOLVEMENT_STATUS = 'Current'
    AND INVOLVEMENT_CODE IN ('COM-KAMP', 'COM-HAK', 'COM-KPETC', 'COM-APEAC', 'COM-KREAC', 'COM-KWLC', 'COM-KAYAB', 'COM-MBAAC', 'COM-KTC')
  GROUP BY CONSTITUENT_DONOR_ID
)

,PREF_SCHOOLS AS (
  SELECT
    CONSTITUENT_DONOR_ID
    ,ROW_NUMBER() OVER(PARTITION BY CONSTITUENT_DONOR_ID ORDER BY DEGREE_DETAIL_SID ASC)RW
    ,DEGREE_YEAR
    ,DEGREE_SCHOOL_NAME
  FROM DM_ALUMNI.DIM_DEGREE_DETAIL
  WHERE DEGREE_NORTHWESTERN_UNIVERSITY_INDICATOR = 'Y'
  AND DEGREE_YEAR IS NOT NULL
)

/*STEWARDSHIP*/  --RECOGNITION CREDIT IS THE NEW STEWARDSHIP
,STEWARDSHIP_DETER AS (
    SELECT
      CREDITED_DONOR_ID
      ,SUM(CASE WHEN CAL.CURR_FY = FISCAL_YEAR THEN RECOGNITION_CREDIT ELSE 0 END) AS stewardship_cfy
      ,SUM(CASE WHEN CAL.CURR_FY = FISCAL_YEAR +1 THEN RECOGNITION_CREDIT ELSE 0 END) AS stewardship_pfy1
      ,SUM(CASE WHEN CAL.CURR_FY = FISCAL_YEAR +2 THEN RECOGNITION_CREDIT ELSE 0 END) AS stewardship_pfy2
      ,SUM(CASE WHEN CAL.CURR_FY = FISCAL_YEAR +3 THEN RECOGNITION_CREDIT ELSE 0 END) AS stewardship_pfy3
    FROM MV_KSM_TRANSACTIONS
    CROSS JOIN DTS CAL
    GROUP BY CREDITED_DONOR_ID
)

,STW_LOYAL AS (
  SELECT
    CREDITED_DONOR_ID
    ,STEWARDSHIP_CFY
    ,STEWARDSHIP_PFY1
    ,STEWARDSHIP_PFY2
    ,STEWARDSHIP_PFY3
    , Case When stewardship_cfy > 0 And stewardship_pfy1 > 0 And stewardship_pfy2 > 0 Then 'Y' End As loyal_this_year
    , Case When stewardship_pfy1 > 0 And stewardship_pfy2 > 0 And stewardship_pfy3 > 0 Then 'Y' End As loyal_last_year
  FROM STEWARDSHIP_DETER
)

/*TRANSACTIONS*/
,GIVING AS (
  SELECT
    *
  FROM MV_KSM_TRANSACTIONS
)

,CASH_ONLY AS (
  SELECT
  G.CREDITED_DONOR_ID
  ,G.TX_ID
  ,G.OPPORTUNITY_RECORD_ID
  ,G.FISCAL_YEAR
  ,G.LEGACY_ALLOCATION_CODE
  ,G.CREDIT_AMOUNT
  FROM  GIVING G
  CROSS JOIN DTS MD
  WHERE G.GYPM_IND NOT IN ('P', 'M')
    AND G.KSM_CRU_FLAG = 'Y'
    AND G.FISCAL_YEAR IN (MD.CURR_FY, MD.CURR_FY-1, MD.CURR_FY-2)
)

,MATCHES AS (
  SELECT
    G.CREDITED_DONOR_ID
    ,G.MATCHED_GIFT_RECORD_ID
    ,G.LEGACY_ALLOCATION_CODE
    ,SUM(G.CREDIT_AMOUNT) MTCH
   FROM GIVING G
   CROSS JOIN DTS MD
   WHERE G.GYPM_IND = 'M'
     AND G.KSM_CRU_FLAG = 'Y'
     AND G.FISCAL_YEAR IN (MD.CURR_FY, MD.CURR_FY-1, MD.CURR_FY-2)
   GROUP BY G.CREDITED_DONOR_ID, G.MATCHED_GIFT_RECORD_ID, G.LEGACY_ALLOCATION_CODE
)

/*CLAIMS????*/
--GYPM_IND NULL BUT SAYS MATCHING GIFT that's a claim

,KGF_REWORKED AS (
  SELECT
    ID
    ,FY
    ,SUM(AMT) AS TOT_KGIFTS
  FROM (
    SELECT
      HH.CREDITED_DONOR_ID ID
      ,HH.OPPORTUNITY_RECORD_ID
      ,HH.FISCAL_YEAR FY
      ,(HH.CREDIT_AMOUNT + NVL(MTC.MTCH,0)) AMT
     FROM CASH_ONLY HH
     CROSS JOIN DTS MD
     LEFT JOIN MATCHES MTC
       ON HH.CREDITED_DONOR_ID = MTC.CREDITED_DONOR_ID
       AND HH.OPPORTUNITY_RECORD_ID = MTC.MATCHED_GIFT_RECORD_ID
       AND HH.LEGACY_ALLOCATION_CODE = MTC.LEGACY_ALLOCATION_CODE
     WHERE HH.FISCAL_YEAR IN (MD.CURR_FY, MD.CURR_FY-1, MD.CURR_FY-2))
   CROSS JOIN DTS MD
   GROUP BY ID, FY
)

,MANUAL_KLC AS (
SELECT DISTINCT
   UCINN_ASCENDV2__DONOR_ID_FORMULA__C AS ID_NUMBER
   ,ucinn_ascendv2__expiration_date__c
   ,EXTRACT(YEAR FROM ucinn_ascendv2__expiration_date__c) AS FISCAL_YEAR
FROM stg_alumni.ucinn_ascendv2__society_membership__c
CROSS JOIN DTS
WHERE (UCINN_ASCENDV2__COMMENTS__C LIKE '%per email%'
  OR UCINN_ASCENDV2__COMMENTS__C LIKE '%email%')
  AND AP_GIVING_SOCIETY_NAME_TEXT__C = 'Kellogg Leadership Circle'
  AND (EXTRACT(YEAR FROM ucinn_ascendv2__member_since__c) <= DTS.CURR_FY
      AND EXTRACT(YEAR FROM ucinn_ascendv2__expiration_date__c) >= DTS.CURR_FY-2)
UNION
SELECT DISTINCT
  UCINN_ASCENDV2__DONOR_ID_FORMULA__C AS ID_NUMBER
  ,ucinn_ascendv2__expiration_date__c
  ,EXTRACT(YEAR FROM ucinn_ascendv2__member_since__c) AS FISCAL_YEAR
FROM stg_alumni.ucinn_ascendv2__society_membership__c
CROSS JOIN DTS
WHERE (UCINN_ASCENDV2__COMMENTS__C LIKE '%per email%'
  OR UCINN_ASCENDV2__COMMENTS__C LIKE '%email%')
  AND AP_GIVING_SOCIETY_NAME_TEXT__C = 'Kellogg Leadership Circle'
  AND (EXTRACT(YEAR FROM ucinn_ascendv2__member_since__c) <= DTS.CURR_FY
      AND EXTRACT(YEAR FROM ucinn_ascendv2__expiration_date__c) >= DTS.CURR_FY-2)
)

,KLC_LISTAGG AS (  /*NOT QUITE RIGHT BUT PLACEHOLDER, IS WORKING CORRECT USING CASHONLY*/
  SELECT
    KGF.ID AS ID_NUMBER
    ,LISTAGG(KGF.FY, ', ') WITHIN GROUP (ORDER BY KGF.FY DESC) AS KLC_YEARS
  FROM KGF_REWORKED KGF
  CROSS JOIN DTS MD
  LEFT JOIN KSM_DEG KD
  ON KGF.ID = KD.DONOR_ID
  WHERE (KD.LAST_NONCERT_YEAR BETWEEN MD.CURR_FY-5 AND MD.CURR_FY AND KGF.TOT_KGIFTS >= 1000)
    OR KGF.TOT_KGIFTS >= 2500
  GROUP BY KGF.ID
  UNION
    SELECT
      ID_NUMBER
      ,LISTAGG(MK.FISCAL_YEAR, ', ') WITHIN GROUP (ORDER BY MK.FISCAL_YEAR DESC) AS KLC_YEARS
    FROM MANUAL_KLC MK
    GROUP BY ID_NUMBER
)

,KLC_YEARS AS (
  SELECT DISTINCT
    ID_NUMBER
    ,LISTAGG(KLC_YEARS, ', ') WITHIN GROUP (ORDER BY KLC_YEARS DESC) AS KLC_YEARS
  FROM KLC_LISTAGG
  GROUP BY ID_NUMBER
)

/*SALUTATIONS*/
,DEAN_SAL_ORDER AS (
 SELECT
  ME.DONOR_ID
  ,ROW_NUMBER() OVER(PARTITION BY ME.DONOR_ID ORDER BY SAL.CREATEDDATE DESC)RW
  ,SAL.UCINN_ASCENDV2__INSIDE_SALUTATION__C as SALUTATION
FROM MV_ENTITY ME
INNER JOIN stg_alumni.ucinn_ascendv2__salutation__c SAL
ON ME.SALESFORCE_ID = SAL.UCINN_ASCENDV2__CONTACT__C
WHERE SAL.UCINN_ASCENDV2__AUTHOR_TITLE__C = 'Dean of Kellogg School of Management'
  AND SAL.UCINN_ASCENDV2__SALUTATION_RECORD_TYPE_FORMULA__C = 'Ind'
)

,DEAN_SAL AS (
 SELECT
   *
 FROM DEAN_SAL_ORDER
 WHERE RW = 1
)

/*FAC_STAFF*/
,facstaff AS (
  SELECT
    CONSTITUENT_DONOR_ID
    ,INSTITUTIONAL_SUFFIX
    ,'Faculty/Staff' AS SHORT_DESC
  FROM DM_ALUMNI.DIM_CONSTITUENT
  WHERE CONSTITUENT_TYPE LIKE '%Faculty%'
)

/*ADDRESSES*/
,PREF_ADDRESS AS (
  SELECT
    E.DONOR_ID
    ,E.PREFERRED_ADDRESS_TYPE
    ,E.PREFERRED_ADDRESS_STATUS
    ,CASE WHEN E.PREFERRED_ADDRESS_TYPE = 'Business' THEN DA.EMPLOYEE_JOB_TITLE ELSE ' ' END AS JOB_TITLE
    ,CASE WHEN E.PREFERRED_ADDRESS_TYPE = 'Business' THEN DA.EMPLOYER_ORGANIZATION_NAME ELSE ' ' END AS COMPANY_NAME
    ,E.PREFERRED_ADDRESS_CITY || ', '|| E.PREFERRED_ADDRESS_STATE || ' ' || E.PREFERRED_ADDRESS_POSTAL_CODE AS "CITY_STATE_ZIP"
    ,E.PREFERRED_ADDRESS_LINE_1
    ,E.PREFERRED_ADDRESS_LINE_2
    ,E.PREFERRED_ADDRESS_LINE_3
    ,E.PREFERRED_ADDRESS_LINE_4
    ,E.PREFERRED_ADDRESS_CITY
    ,E.PREFERRED_ADDRESS_STATE
    ,E.PREFERRED_ADDRESS_POSTAL_CODE
    ,E.PREFERRED_ADDRESS_COUNTRY
  FROM MV_ENTITY E
  LEFT JOIN DM_ALUMNI.DIM_AFFILIATION DA
  ON E.DONOR_ID = DA.CONSTITUENT_DONOR_ID
    AND DA.PRIMARY_EMPLOYMENT_INDICATOR = 'Y'
)

,PRES_ADDRESS AS (
  SELECT DISTINCT
    ME.DONOR_ID
    ,AC.Ucinn_Ascendv2__Presidential_Preferred_Street__c AS PRES_PREF_STREET
    ,AC.UCINN_ASCENDV2__PRESIDENTIAL_PREFERRED_CITY__C AS PRES_PREF_CITY
    ,AC.UCINN_ASCENDV2__PRESIDENTIAL_PREFERRED_STATE__C AS PRES_PREF_STATE
    ,AC.UCINN_ASCENDV2__PRESIDENTIAL_PREFERRED_POSTAL_CODE__C AS PRES_PREF_POSTAL_CODE
    ,AC.UCINN_ASCENDV2__PRESIDENTIAL_PREFERRED_COUNTRY__C AS PRES_PREF_COUNTRY
  FROM MV_ENTITY ME
  INNER JOIN stg_alumni.contact AC
  ON ME.SALESFORCE_ID = AC.ID
)

/* Transaction and pledge TMS table definition */ /*NOT SURE WHAT THIS IS USED FOR */
,TMS_TRANS AS (
    SELECT DISTINCT
      OPPORTUNITY_TYPE
    FROM MV_KSM_TRANSACTIONS
)

,FIRST_GIFT AS (
  SELECT
    CREDITED_DONOR_ID
    ,MIN(CREDIT_DATE) AS FIRST_KSM_GIFT_DT
  FROM MV_KSM_TRANSACTIONS
  WHERE OPPORTUNITY_TYPE <> 'Telefund' -- SHOULD THIS ALSO INCLUDE SOURCE_TYPE_DETAIL? PLEDGE/PLEDGE PAYMENT
  GROUP BY CREDITED_DONOR_ID
)

/*JOINT GIFTS??????*/
,JOINT_IND AS (
  SELECT
    MKT.OPPORTUNITY_RECORD_ID
    ,MKT.HARD_AND_SOFT_CREDIT_SALESFORCE_ID
    ,'Y' AS JOINT_IND
  FROM MV_KSM_TRANSACTIONS MKT
  INNER JOIN DM_ALUMNI.DIM_CONSTITUENT DC
  ON MKT.CREDITED_DONOR_ID = DC.CONSTITUENT_DONOR_ID
  WHERE DC.SALUTATION_PREFERENCE = 'Joint'
    OR DC.MARITAL_STATUS = 'Married'
)

/*TRANSACTIONS TO USE*/
,trans AS (
  SELECT
    MKT.CREDIT_RECEIPT_NUMBER
    ,MKT.OPPORTUNITY_RECORD_ID
    ,MKT.HARD_AND_SOFT_CREDIT_SALESFORCE_ID
  FROM MV_KSM_TRANSACTIONS MKT
  CROSS JOIN DTS
  WHERE MKT.CREDIT_DATE BETWEEN DTS.dt1 and dts.dt2
     AND MKT.ADJUSTED_OPPORTUNITY_IND IS NULL
    --AND MKT.OPPORTUNITY_TYPE <> 'Matching'
     AND MKT.GYPM_IND <> 'M'
)

, assoc_dnrs As (
  SELECT
    MKT.OPPORTUNITY_RECORD_ID
    ,MKT.TX_ID
    ,MKT.PAYMENT_RECORD_ID
    ,MKT.HARD_AND_SOFT_CREDIT_SALESFORCE_ID
    ,MKT.CREDIT_TYPE
    ,MKT.CREDIT_RECEIPT_NUMBER
    ,MKT.LEGACY_ALLOCATION_CODE
    ,MKT.DESIGNATION_NAME
    ,MKT.CREDITED_DONOR_ID
    --,MKT.CREDITED_DONOR_NAME
    ,CASE WHEN ME.PERSON_OR_ORG = 'O' THEN ME.SORT_NAME ELSE SAL.UCINN_ASCENDV2__ADDRESSEE_LINE_1__C END AS CREDITED_DONOR_NAME
    ,ME.SALESFORCE_ID
    ,ME.INSTITUTIONAL_SUFFIX
    ,NVL(KSM_DEG.DEGREES_CONCAT, ' ') AS DEGREES_CONCAT
    , nvl(gab.gab_role, ' ') As gab_role
    , nvl(kac.kac_role, ' ') AS kac_role
    , nvl(t.trustee_role, ' ') AS trustee_role
    , nvl(keba.keba_role, ' ') AS keba_role
    , nvl(boards.committees, ' ') AS board_committees
    , nvl(facstaff.short_desc, ' ') As facstaff
    , nvl(klc_years.klc_years, ' ') As klc_years
    ,first_gift.FIRST_KSM_GIFT_DT
    , stw_loyal.loyal_this_year, stw_loyal.loyal_last_year
    , rank() Over (
       /* PARTITION BY MKT.OPPORTUNITY_RECORD_ID, MKT.TX_ID, MKT.LEGACY_ALLOCATION_CODE
        ORDER BY MKT.OPPORTUNITY_RECORD_ID ASC, MKT.LEGACY_ALLOCATION_CODE ASC, MKT.HARD_AND_SOFT_CREDIT_SALESFORCE_ID ASC,
          MKT.CREDIT_TYPE ASC*/
        PARTITION BY MKT.TX_ID,MKT.LEGACY_ALLOCATION_CODE
        ORDER BY MKT.OPPORTUNITY_RECORD_ID ASC, MKT.LEGACY_ALLOCATION_CODE ASC, MKT.CREDIT_TYPE ASC,
        MKT.HARD_AND_SOFT_CREDIT_SALESFORCE_ID ASC
      ) AS ATTR_DONOR_RANK
        --Partition By gft.tx_number, gft.alloc_short_name
      --  Order By gft.tx_number Asc, gft.alloc_short_name Asc, gft.tx_sequence Asc
     --) As attr_donor_rank
  FROM MV_KSM_TRANSACTIONS MKT
  CROSS JOIN DTS
  INNER JOIN MV_ENTITY ME
    ON MKT.CREDITED_DONOR_ID = ME.DONOR_ID
  LEFT JOIN stg_alumni.ucinn_ascendv2__salutation__c  SAL
    ON ME.salesforce_id = SAL.ucinn_ascendv2__contact__c
  AND SAL.UCINN_ASCENDV2__SALUTATION_TYPE__C = 'Formal'
  AND SAL.UCINN_ASCENDV2__SALUTATION_RECORD_TYPE_FORMULA__C = 'Ind'
  LEFT JOIN KSM_DEG
    ON KSM_DEG.DONOR_ID = MKT.CREDITED_DONOR_ID
  LEFT JOIN MV_ENTITY ME
  ON MKT.CREDITED_DONOR_ID = ME.DONOR_ID
  Left Join gab On gab.id_number = MKT.CREDITED_DONOR_ID
  LEFT JOIN kac on kac.id_number = MKT.CREDITED_DONOR_ID
  left join boards on boards.id_number = MKT.CREDITED_DONOR_ID
  LEFT JOIN keba on keba.id_number = MKT.CREDITED_DONOR_ID
  Left Join facstaff On facstaff.CONSTITUENT_DONOR_ID = MKT.CREDITED_DONOR_ID
  Left Join klc_years On klc_years.id_number = MKT.CREDITED_DONOR_ID
  LEFT JOIN trustee t on t.id_number = MKT.CREDITED_DONOR_ID
  Left Join first_gift On first_gift.CREDITED_DONOR_ID = MKT.CREDITED_DONOR_ID
  Left Join stw_loyal On stw_loyal.CREDITED_DONOR_ID = MKT.CREDITED_DONOR_ID
  WHERE MKT.CREDIT_DATE BETWEEN DTS.dt1 and dts.dt2
    --AND MKT.OPPORTUNITY_RECORD_ID = 'GN1953170'
    --AND MKT.OPPORTUNITY_TYPE <> 'Matching'
)

, assoc_dnr_count AS (
  SELECT
    OPPORTUNITY_RECORD_ID
    ,TX_ID
    ,COUNT(CREDITED_DONOR_ID) AS assoc_donor_count
  FROM assoc_dnrs
  GROUP BY OPPORTUNITY_RECORD_ID, TX_ID
)

, assoc_concat As ( -- Multiple id_numbers per line, separated by carriage return
/*  Select
    OPPORTUNITY_RECORD_ID
    ,TX_ID
    , DESIGNATION_NAME
    , Listagg(institutional_suffix, ';  ') Within Group (Order By HARD_AND_SOFT_CREDIT_SALESFORCE_ID) As inst_suffixes
    , Listagg(trim(CREDITED_DONOR_NAME) || ' (#' || CREDITED_DONOR_ID || ')', ';  ') Within Group (Order By HARD_AND_SOFT_CREDIT_SALESFORCE_ID) As assoc_donors
    , Listagg(degrees_concat, ';  ') Within Group (Order By HARD_AND_SOFT_CREDIT_SALESFORCE_ID) As assoc_degrees
    , Listagg(gab_role, ';  ') Within Group (Order By HARD_AND_SOFT_CREDIT_SALESFORCE_ID) As assoc_gab
    , Listagg(kac_role, ';  ') Within Group (Order by HARD_AND_SOFT_CREDIT_SALESFORCE_ID) AS assoc_kac
    , Listagg(trustee_role, '; ') Within Group (order by HARD_AND_SOFT_CREDIT_SALESFORCE_ID) as assoc_trustee
    , Listagg(keba_role, '; ') Within Group (order by HARD_AND_SOFT_CREDIT_SALESFORCE_ID) as assoc_keba
    , Listagg(board_committees, '; ') Within Group (Order by HARD_AND_SOFT_CREDIT_SALESFORCE_ID) as assoc_boards
    , Listagg(facstaff, ';  ') Within Group (Order By HARD_AND_SOFT_CREDIT_SALESFORCE_ID) As assoc_facstaff
    , Listagg(klc_years, ';  ') Within Group (Order By HARD_AND_SOFT_CREDIT_SALESFORCE_ID) As assoc_klc
    , Listagg(to_char(first_ksm_gift_dt,'MM/DD/YYYY'), ';  ') Within Group (Order By HARD_AND_SOFT_CREDIT_SALESFORCE_ID) As first_ksm_gifts
    , Listagg(loyal_this_year, ';  ') Within Group (Order By HARD_AND_SOFT_CREDIT_SALESFORCE_ID) As loyal_this_fy
    , Listagg(loyal_last_year, ';  ') Within Group (Order By HARD_AND_SOFT_CREDIT_SALESFORCE_ID) As loyal_last_fy
  From assoc_dnrs
  Group By
    OPPORTUNITY_RECORD_ID
    ,TX_ID
    , DESIGNATION_NAME*/
  Select
    OPPORTUNITY_RECORD_ID
    ,TX_ID
    , DESIGNATION_NAME
    , Listagg(institutional_suffix, ';  ') Within Group (Order By CREDIT_TYPE ASC, HARD_AND_SOFT_CREDIT_SALESFORCE_ID) As inst_suffixes
    , Listagg(trim(CREDITED_DONOR_NAME) || ' (#' || CREDITED_DONOR_ID || ')', ';  ') Within Group (Order By CREDIT_TYPE ASC, HARD_AND_SOFT_CREDIT_SALESFORCE_ID) As assoc_donors
    , Listagg(degrees_concat, ';  ') Within Group (Order By CREDIT_TYPE ASC, HARD_AND_SOFT_CREDIT_SALESFORCE_ID) As assoc_degrees
    , Listagg(gab_role, ';  ') Within Group (Order By CREDIT_TYPE ASC, HARD_AND_SOFT_CREDIT_SALESFORCE_ID) As assoc_gab
    , Listagg(kac_role, ';  ') Within Group (Order by CREDIT_TYPE ASC, HARD_AND_SOFT_CREDIT_SALESFORCE_ID) AS assoc_kac
    , Listagg(trustee_role, '; ') Within Group (order by CREDIT_TYPE ASC, HARD_AND_SOFT_CREDIT_SALESFORCE_ID) as assoc_trustee
    , Listagg(keba_role, '; ') Within Group (order by CREDIT_TYPE ASC, HARD_AND_SOFT_CREDIT_SALESFORCE_ID) as assoc_keba
    , Listagg(board_committees, '; ') Within Group (Order by CREDIT_TYPE ASC, HARD_AND_SOFT_CREDIT_SALESFORCE_ID) as assoc_boards
    , Listagg(facstaff, ';  ') Within Group (Order By CREDIT_TYPE ASC, HARD_AND_SOFT_CREDIT_SALESFORCE_ID) As assoc_facstaff
    , Listagg(klc_years, ';  ') Within Group (Order By CREDIT_TYPE ASC, HARD_AND_SOFT_CREDIT_SALESFORCE_ID) As assoc_klc
    , Listagg(to_char(first_ksm_gift_dt,'MM/DD/YYYY'), ';  ') Within Group (Order By CREDIT_TYPE ASC, HARD_AND_SOFT_CREDIT_SALESFORCE_ID) As first_ksm_gifts
    , Listagg(loyal_this_year, ';  ') Within Group (Order By CREDIT_TYPE ASC, HARD_AND_SOFT_CREDIT_SALESFORCE_ID) As loyal_this_fy
    , Listagg(loyal_last_year, ';  ') Within Group (Order By CREDIT_TYPE ASC, HARD_AND_SOFT_CREDIT_SALESFORCE_ID) As loyal_last_fy
  From assoc_dnrs
  Group By
    OPPORTUNITY_RECORD_ID
    ,TX_ID
    , DESIGNATION_NAME

)



/*MAIN QUERY*/
SELECT DISTINCT
  /*Case When gft.transaction_type In ('BE', 'LE') And gft.nwu_std_alloc_group = 'UO'
    Then pledge.pledge_program_code
    Else gft.nwu_std_alloc_group
  End As nwu_std_alloc_group*/
  MKT.CREDITED_DONOR_ID
  ,CASE WHEN ME.PERSON_OR_ORG = 'O' THEN ME.SORT_NAME ELSE SAL.UCINN_ASCENDV2__ADDRESSEE_LINE_1__C END AS PREF_MAIL_NAME
  ,ME.SORT_NAME AS REPORT_NAME
  ,ASSOC.ASSOC_DONORS
  , Case When trim(assoc.assoc_degrees) <> ';' Then trim(assoc.assoc_degrees) End As assoc_degrees
  , assoc.inst_suffixes
  , assoc.first_ksm_gifts
  , CASE WHEN adr.assoc_donor_count >= 2 then 'Y' ELSE ' ' END AS assc_donor_count_flag
  , CASE when trim(assoc.assoc_trustee) <> ';' THEN trim(assoc.assoc_trustee) END AS assoc_trustee
  , CASE WHEN trim(assoc.assoc_keba) <> ';' THEN trim(assoc.assoc_keba) END AS assoc_keba
  , CASE WHEN trim(assoc.assoc_boards) <> ';' THEN trim(assoc.assoc_boards) END AS assoc_boards
  , Case When trim(assoc.assoc_facstaff) <> ';' Then trim(assoc.assoc_facstaff) End As assoc_facstaff
  , Case When trim(assoc.assoc_gab) <> ';' Then trim(assoc.assoc_gab) End As assoc_gab
  , CASE WHEN trim(assoc.assoc_kac) <> ';' THEN trim(assoc.assoc_kac) END AS assoc_kac
  , Case When trim(assoc.assoc_klc) <> ';' Then trim(assoc.assoc_klc) End As assoc_klc
 -- ,'NEED' AS NWU_TRUSTEE_CREDIT--NU TRUSTEE CREDIT can I just use the Y from V_COMMITTEE_TRUSTEE?
  , assoc.loyal_this_fy
  , assoc.loyal_last_fy
  -- Joint gift data
  , Case When joint_ind.joint_ind Is Not Null Then 'Y' Else 'N' End As joint_ind
  , Case When joint_ind.joint_ind Is Not Null Then ME.SPOUSE_DONOR_ID End As joint_id_number
  , Case When joint_ind.joint_ind Is Not Null Then SSAL.UCINN_ASCENDV2__ADDRESSEE_LINE_1__C END AS JOINT_NAME
  , DSAL.SALUTATION  AS DEAN_SALUTATION1
  , SDSAL.SALUTATION  AS DEAN_SALUTATION2
  , DC.FIRST_NAME AS FIRST_NAME1
  , SDC.FIRST_NAME AS FIRST_NAME2
  ,ME.PRIMARY_RECORD_TYPE AS RECORD_TYPE
  ,DC.SPOUSE_PRIMARY_CONSTITUENT_TYPE AS JOINT_RECORD_TYPE
  ,PS.DEGREE_YEAR AS PREF_CLASS_YEAR
  ,PS.DEGREE_SCHOOL_NAME AS PREF_SCHOOL
  , ksm_deg.program_group As ksm_program
  , ksm_deg.degrees_concat As ksm_degrees
  , Case When joint_ind.joint_ind Is Not Null Then jksm_deg.program_group End As joint_ksm_program
  , Case When joint_ind.joint_ind Is Not Null Then jksm_deg.degrees_concat End As joint_ksm_degrees
  /*ADDRESS INFO*/
    -- Address data for tableau
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN KSM_DEG2.DEGREES_CONCAT ELSE KSM_DEG.DEGREES_CONCAT
         END AS PRIMARY_DEGREE_CONCAT
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN entitydnr2.UCINN_ASCENDV2__ADDRESSEE_LINE_1__C ELSE SAL.UCINN_ASCENDV2__ADDRESSEE_LINE_1__C
          END AS PRIMARY_DONOR_NAME
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN MEDNR2.FIRST_NAME ELSE DC.FIRST_NAME
          END AS SALUTATION_1
   , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN MEDNR3.FIRST_NAME ELSE MEDNR2.FIRST_NAME
          END AS SALUTATION_2
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr2.PREFERRED_ADDRESS_TYPE ELSE addr.PREFERRED_ADDRESS_TYPE
          END AS ADDRESS_TYPE
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr2.JOB_TITLE ELSE addr.JOB_TITLE
         END AS JOB_TITLE
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr2.COMPANY_NAME ELSE addr.COMPANY_NAME
         END AS COMPANY_NAME
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr2.CITY_STATE_ZIP ELSE addr.CITY_STATE_ZIP
         END AS CITY_STATE_ZIP
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr2.PREFERRED_ADDRESS_LINE_1 ELSE addr.PREFERRED_ADDRESS_LINE_1
         END AS ADDRESS_LINE_1
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr2.PREFERRED_ADDRESS_LINE_2 ELSE addr.PREFERRED_ADDRESS_LINE_2
          END AS ADDRESS_LINE_2
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr2.PREFERRED_ADDRESS_LINE_3 ELSE addr.PREFERRED_ADDRESS_LINE_3
          END AS ADDRESS_LINE_3
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr2.PREFERRED_ADDRESS_LINE_4 ELSE addr.PREFERRED_ADDRESS_LINE_4
          END AS ADDRESS_LINE_4
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr2.PREFERRED_ADDRESS_CITY ELSE addr.PREFERRED_ADDRESS_CITY
         END AS ADDRESS_LINE_5
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr2.PREFERRED_ADDRESS_STATE ELSE addr.PREFERRED_ADDRESS_STATE
         END AS ADDRESS_LINE_6
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr2.PREFERRED_ADDRESS_POSTAL_CODE ELSE addr.PREFERRED_ADDRESS_POSTAL_CODE
          END AS ADDRESS_LINE_7
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr2.PREFERRED_ADDRESS_COUNTRY ELSE addr.PREFERRED_ADDRESS_COUNTRY
          END AS ADDRESS_LINE_8
  , CASE WHEN ME.PERSON_OR_ORG = 'P' THEN PRESADDR.PRES_PREF_STREET else ' ' end as PRES_PREF_STREET
  , CASE WHEN ME.PERSON_OR_ORG = 'P' THEN PRESADDR.PRES_PREF_CITY ELSE ' ' END AS PRES_PREF_CITY
  , CASE WHEN ME.PERSON_OR_ORG = 'P' THEN PRESADDR.PRES_PREF_STATE ELSE ' ' END AS PRES_PREF_STATE
  , CASE WHEN ME.PERSON_OR_ORG = 'P' THEN PRESADDR.PRES_PREF_POSTAL_CODE ELSE ' ' END AS PRES_PREF_POSTAL_CODE
  , CASE WHEN ME.PERSON_OR_ORG = 'P' THEN PRESADDR.PRES_PREF_COUNTRY ELSE ' ' END AS PRES_PREF_COUNTRY
  ,CASE WHEN JOINT_IND.JOINT_IND = 'Y' THEN SAL.UCINN_ASCENDV2__ADDRESSEE_LINE_1__C END AS PREF_JNT_MAIL_NAME1
  ,CASE WHEN JOINT_IND.JOINT_IND = 'Y' THEN SSAL.UCINN_ASCENDV2__ADDRESSEE_LINE_1__C END AS PREF_JNT_MAIL_NAME2
 -- ,CASE WHEN JOINT_IND.JOINT_IND = 'Y' THEN JSAL.UCINN_ASCENDV2__INSIDE_SALUTATION__C END AS PREF_JOINT_SALUTATION
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr2.JOB_TITLE ELSE addr.JOB_TITLE
         END AS BUSINESS_TITLE
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr2.COMPANY_NAME ELSE addr.COMPANY_NAME
         END AS COMPANY_NAME1
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr2.CITY_STATE_ZIP ELSE addr.CITY_STATE_ZIP
         END AS CITY_STATE_ZIP1
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr2.PREFERRED_ADDRESS_LINE_1
          ELSE addr.PREFERRED_ADDRESS_LINE_1 END AS STREET1
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr2.PREFERRED_ADDRESS_LINE_2 ELSE addr.PREFERRED_ADDRESS_LINE_2
          END AS STREET2
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr2.PREFERRED_ADDRESS_LINE_3 ELSE addr.PREFERRED_ADDRESS_LINE_3
         END AS STREET3
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr2.PREFERRED_ADDRESS_CITY ELSE addr.PREFERRED_ADDRESS_CITY
          END AS CITY
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr2.PREFERRED_ADDRESS_STATE ELSE addr.PREFERRED_ADDRESS_STATE
          END AS STATE
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr2.PREFERRED_ADDRESS_POSTAL_CODE ELSE addr.PREFERRED_ADDRESS_POSTAL_CODE
          END AS ZIP
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr2.PREFERRED_ADDRESS_COUNTRY ELSE addr.PREFERRED_ADDRESS_COUNTRY
          END AS COUNTRY
  ,MKT.GYPM_IND
  ,MKT.OPPORTUNITY_RECORD_ID
  ,MKT.TX_ID
 -- ,MKT.CREDIT_RECEIPT_NUMBER
  , CASE WHEN DCAMP.CAMPAIGN_MOTIVATION_CODE IN ('MAYKA', 'LAYKA', 'NAYKA', 'PAYKA', 'QAYKA') THEN 'Y' ELSE 'N' END AS "FROM CVENT"
  ,MKT.OPPORTUNITY_TYPE
  ,MKT.SOURCE_TYPE_DETAIL
    /*PLEDGE INFO*/
  ,CASE WHEN MKT.GYPM_IND = 'Y' THEN MKT.OPPORTUNITY_RECORD_ID ELSE ' ' END AS "PMT_ON_PLEDGE_NUMBER"
  ,CASE WHEN MKT.OPPORTUNITY_RECORD_ID LIKE 'PN%' THEN DO.OPPORTUNITY_NOTES ELSE ' ' END AS PLEDGE_COMMENT
 -- ,'NEED' AS PLEDGE_PAYMENT_SCHEDULE_CODE
 -- ,'NEED' AS PLEDGE_PAYMENT_SCHEDULE
  ,MKT.PAYMENT_SCHEDULE
  ,MKT.CREDIT_DATE
  ,MKT.Entry_Date
  ,MKT.TRIBUTE_TYPE AS MEMORY_HONOR_OF_IND
  ,MKT.TRIBUTEES AS MEMORY_HONOR_OF
 -- ,'NEED' AS REASON_CHANGED
--  ,'NEED' AS REASON_CHANGED_DATE
  ,PAY.AP_RECEIPT_DATE__C
  ,CASE WHEN MKT.OPPORTUNITY_RECORD_ID LIKE 'GN%' THEN DO.OPPORTUNITY_NOTES ELSE ' ' END AS GIFT_COMMENT
 -- ,PAYMENT.AP_Receipt_Date__c AS DATE_OF_RECEIPT
 -- ,PAYMENT.UCINN_ASCENDV2__NOTES__C AS GIFT_COMMENT
  , Case When trunc(MKT.CREDIT_DATE) = trunc(first_gift.first_ksm_gift_dt) Then 'Y' End As first_gift
  ,PAY.AP_PROCESSED_DATE__C
  ,MKT.TENDER_TYPE
  ,MKT.CREDIT_AMOUNT
  ,MKT.DESIGNATION_NAME
  --,MKT.ADJUSTED_OPPORTUNITY_IND  PAUL WORKING TO ADD THIS, IN THE MEANTIME BELOW
  ,PAY.UCINN_ASCENDV2__ADJUSTMENT_TYPE__C AS ADJUSTED_GIFT
  ,ADJOP.NAME AS ORIGINAL_OPPORTUNITY_RECORD_ID
  ,ADJOP.UCINN_ASCENDV2__ADJUSTMENT_REASON_V1__C AS ADJUSTMENT_REASON
  ,MKT.ANONYMOUS_TYPE AS ANONYMOUS_GIFT
  ,MKT.KSM_CRU_FLAG
  ,MKD.DESIGNATION_TIER_2 AS ALLOC_PURPOSE_DESC
  , Case
      When lower(MKT.DESIGNATION_NAME) Like '%scholarship%' /*Or lower(gft.alloc_purpose_desc) Like '%scholarship%'*/
         Then 'Y'
    End As scholarship_flag
  ,DCAMP.CAMPAIGN_MOTIVATION_CODE
  ,DO.PRIMARY_CAMPAIGN_SOURCE --IS THIS appeal_header.description As appeal_desc
  -- Prospect fields
  ,CASE WHEN ME.PERSON_OR_ORG = 'O' THEN ODSTRAT.STRATEGY_PRIMARY_RELATION_PRIMARY_RELATIONSHIP_MANAGER_NAME
     ELSE DSTRAT.STRATEGY_PRIMARY_RELATION_PRIMARY_RELATIONSHIP_MANAGER_NAME END AS PROSPECT_MANAGER -- PROSPECT MANAGER?
  ,CASE WHEN ME.PERSON_OR_ORG = 'O' THEN ODSTRAT.STRATEGY_PRIMARY_RELATION_UNIVERSITY_OVERALL_RATING
     ELSE DSTRAT.STRATEGY_PRIMARY_RELATION_UNIVERSITY_OVERALL_RATING END AS OFFICER_RATING
  ,CASE WHEN ME.PERSON_OR_ORG = 'O' THEN ODSTRAT.STRATEGY_PRIMARY_RELATION_RESEARCH_EVALUATION
     ELSE DSTRAT.STRATEGY_PRIMARY_RELATION_RESEARCH_EVALUATION END AS EVALUATION_RATING --
  ,CASE WHEN ME.PERSON_OR_ORG = 'O' THEN ODSTRAT.STRATEGY_PRIMARY_RELATION_PRIMARY_RELATIONSHIP_MANAGER_BUSINESS_UNIT
     ELSE DSTRAT.STRATEGY_PRIMARY_RELATION_PRIMARY_RELATIONSHIP_MANAGER_BUSINESS_UNIT END AS TEAM
  ,DTS.CURR_FY
  -- Associated donor 2 information
  , dnr2.CREDITED_DONOR_ID As assoc2_id_number
  ,entitydnr2.UCINN_ASCENDV2__ADDRESSEE_LINE_1__C as assoc2_pref_mail_name
 -- ,jentitydnr2.ucinn_ascendv2__inside_salutation__c as assoc2_pref_joint_mail
  ,CASE WHEN JOINT_IND.JOINT_IND = 'Y' THEN SAL.UCINN_ASCENDV2__ADDRESSEE_LINE_1__C END AS ASSOC2_PREF_JNT_MAIL_NAME1
  ,CASE WHEN JOINT_IND.JOINT_IND = 'Y' THEN SSAL.UCINN_ASCENDV2__ADDRESSEE_LINE_1__C END AS ASSOC2_PREF_JNT_MAIL_NAME2
 -- , entitydnr2.full_name AS assoc2_pref_mail_name
  --, entitydnr2.pref_jnt_mail_name1 AS assoc2_pref_jnt_mail_name1
  --, entitydnr2.pref_jnt_mail_name2 AS assoc2_pref_jnt_mail_name2
--Preferred Address
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr3.PREFERRED_ADDRESS_TYPE ELSE addrdnr2.PREFERRED_ADDRESS_TYPE
          END AS ASSOCIATED_ADDRESS_TYPE
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr3.JOB_TITLE ELSE addrdnr2.JOB_TITLE
         END AS ASSOCIATED_DONOR_JOB_TITLE
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr3.COMPANY_NAME ELSE addrdnr2.COMPANY_NAME
         END AS ASSOCIATED_DONOR_COMPANY_NAME
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN entitydnr3.UCINN_ASCENDV2__ADDRESSEE_LINE_1__C ELSE entitydnr2.UCINN_ASCENDV2__ADDRESSEE_LINE_1__C
          END AS ASSOCIATED_DONOR_NAME
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr3.PREFERRED_ADDRESS_LINE_1 ELSE addrdnr2.PREFERRED_ADDRESS_LINE_1
         END AS ASSOCIATED_ADDRESS_LINE_1
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr3.PREFERRED_ADDRESS_LINE_2 ELSE addrdnr2.PREFERRED_ADDRESS_LINE_2
          END AS ASSOCIATED_ADDRESS_LINE_2
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr3.PREFERRED_ADDRESS_LINE_3 ELSE addrdnr2.PREFERRED_ADDRESS_LINE_3
          END AS ASSOCIATED_ADDRESS_LINE_3
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr3.PREFERRED_ADDRESS_LINE_4 ELSE addrdnr2.PREFERRED_ADDRESS_LINE_4
          END AS ASSOCIATED_ADDRESS_LINE_4
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr3.PREFERRED_ADDRESS_CITY ELSE addrdnr2.PREFERRED_ADDRESS_CITY
         END AS ASSOCIATED_ADDRESS_LINE_5
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr3.PREFERRED_ADDRESS_STATE ELSE addrdnr2.PREFERRED_ADDRESS_STATE
         END AS ASSOCIATED_ADDRESS_LINE_6
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr3.PREFERRED_ADDRESS_POSTAL_CODE ELSE addrdnr2.PREFERRED_ADDRESS_POSTAL_CODE
          END AS ASSOCIATED_ADDRESS_LINE_7
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr3.PREFERRED_ADDRESS_COUNTRY ELSE addrdnr2.PREFERRED_ADDRESS_COUNTRY
          END AS ASSOCIATED_ADDRESS_LINE_8
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr3.PREFERRED_ADDRESS_LINE_1
          ELSE addrdnr2.PREFERRED_ADDRESS_LINE_1 END AS ASSOCIATED_STREET1
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr3.PREFERRED_ADDRESS_LINE_2 ELSE addrdnr2.PREFERRED_ADDRESS_LINE_2
          END AS ASSOCIATED_STREET2
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr3.PREFERRED_ADDRESS_LINE_3 ELSE addrdnr2.PREFERRED_ADDRESS_LINE_3
         END AS ASSOCIATED_STREET3
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr3.PREFERRED_ADDRESS_CITY ELSE addrdnr2.PREFERRED_ADDRESS_CITY
          END AS ASSOCIATED_CITY
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr3.PREFERRED_ADDRESS_STATE ELSE addrdnr2.PREFERRED_ADDRESS_STATE
          END AS ASSOCIATED_STATE
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr3.PREFERRED_ADDRESS_POSTAL_CODE ELSE addrdnr2.PREFERRED_ADDRESS_POSTAL_CODE
          END AS ASSOCIATED_ZIP
  , CASE WHEN ME.PERSON_OR_ORG = 'O' OR ME.PRIMARY_RECORD_TYPE LIKE '%Founda%' or ME.PRIMARY_RECORD_TYPE like '%Corp%'
       OR ME.PRIMARY_RECORD_TYPE Like '%Other%' THEN addrdnr3.PREFERRED_ADDRESS_COUNTRY ELSE addrdnr2.PREFERRED_ADDRESS_COUNTRY
          END AS ASSOCIATED_COUNTRY
  , CASE WHEN ME.PERSON_OR_ORG = 'P' THEN PRESDNR2.PRES_PREF_STREET else ' ' end as ASSOCIATED_PRES_PREF_STREET
  , CASE WHEN ME.PERSON_OR_ORG = 'P' THEN PRESDNR2.PRES_PREF_CITY ELSE ' ' END AS ASSOCIATED_PRES_PREF_CITY
  , CASE WHEN ME.PERSON_OR_ORG = 'P' THEN PRESDNR2.PRES_PREF_STATE ELSE ' ' END AS ASSOCIATED_PRES_PREF_STATE
  , CASE WHEN ME.PERSON_OR_ORG = 'P' THEN PRESDNR2.PRES_PREF_POSTAL_CODE ELSE ' ' END AS ASSOCIATED_PRES_PREF_POSTAL_CODE
  , CASE WHEN ME.PERSON_OR_ORG = 'P' THEN PRESDNR2.PRES_PREF_COUNTRY ELSE ' ' END AS ASSOCIATED_PRES_PREF_COUNTRY
From MV_KSM_TRANSACTIONS MKT
-- Calendar objects
Cross Join dts
Inner Join trans
  On trans.OPPORTUNITY_RECORD_ID = MKT.OPPORTUNITY_RECORD_ID
  And trans.HARD_AND_SOFT_CREDIT_SALESFORCE_ID = MKT.HARD_AND_SOFT_CREDIT_SALESFORCE_ID
INNER JOIN MV_ENTITY ME
ON MKT.CREDITED_DONOR_ID = ME.DONOR_ID
Inner Join assoc_concat assoc
  On assoc.OPPORTUNITY_RECORD_ID = MKT.OPPORTUNITY_RECORD_ID
  And assoc.DESIGNATION_NAME = MKT.DESIGNATION_NAME
  AND ASSOC.TX_ID = MKT.TX_ID
LEFT JOIN mv_households MHH
ON ME.HOUSEHOLD_ID = MHH.HOUSEHOLD_ID
LEFT JOIN MV_ENTITY HHPE
ON MHH.HOUSEHOLD_PRIMARY_DONOR_ID = HHPE.DONOR_ID
LEFT JOIN MV_KSM_DESIGNATION MKD
ON MKT.LEGACY_ALLOCATION_CODE = MKD.LEGACY_ALLOCATION_CODE
LEFT JOIN DM_ALUMNI.DIM_CONSTITUENT  DC
ON MKT.CREDITED_DONOR_ID = DC.CONSTITUENT_DONOR_ID
LEFT JOIN DM_ALUMNI.DIM_ORGANIZATION DCO
ON MKT.CREDITED_DONOR_ID = DCO.ORGANIZATION_DONOR_ID
LEFT JOIN stg_alumni.ucinn_ascendv2__salutation__c  SAL
  ON ME.SALESFORCE_ID = SAL.ucinn_ascendv2__contact__c
  AND SAL.UCINN_ASCENDV2__SALUTATION_TYPE__C = 'Formal'
  AND SAL.UCINN_ASCENDV2__SALUTATION_RECORD_TYPE_FORMULA__C = 'Ind'
LEFT JOIN stg_alumni.ucinn_ascendv2__salutation__c  JSAL
ON ME.salesforce_id = JSAL.ucinn_ascendv2__contact__c
  AND JSAL.UCINN_ASCENDV2__SALUTATION_TYPE__C = 'Formal'
  AND JSAL.UCINN_ASCENDV2__SALUTATION_RECORD_TYPE_FORMULA__C = 'Joint'
LEFT JOIN PREF_SCHOOLS PS
ON MKT.CREDITED_DONOR_ID = PS.CONSTITUENT_DONOR_ID
  AND PS.RW = 1
LEFT JOIN DM_ALUMNI.DIM_CONSTITUENT SDC
ON ME.SPOUSE_DONOR_ID = SDC.CONSTITUENT_DONOR_ID
LEFT JOIN stg_alumni.ucinn_ascendv2__salutation__c  SSAL
ON SDC.CONSTITUENT_SALESFORCE_ID = SSAL.ucinn_ascendv2__contact__c
  AND SSAL.UCINN_ASCENDV2__SALUTATION_TYPE__C = 'Formal'
  AND SSAL.UCINN_ASCENDV2__SALUTATION_RECORD_TYPE_FORMULA__C = 'Ind'
LEFT JOIN DEAN_SAL  DSAL
ON MKT.CREDITED_DONOR_ID = DSAL.DONOR_ID
LEFT JOIN DEAN_SAL  SDSAL
ON SDC.CONSTITUENT_DONOR_ID = SDSAL.DONOR_ID
LEFT JOIN dm_alumni.DIM_OPPORTUNITY DO
ON MKT.OPPORTUNITY_RECORD_ID = DO.OPPORTUNITY_RECORD_ID
LEFT JOIN stg_alumni.ucinn_ascendv2__payment__c PAY
ON MKT.TX_ID = PAY.NAME
LEFT JOIN stg_alumni.opportunity ADJOP
ON PAY.UCINN_ASCENDV2__ADJUSTED_GIFT__C = ADJOP.ID
LEFT JOIN DM_ALUMNI.DIM_CAMPAIGN DCAMP
ON DO.CAMPAIGN_SALESFORCE_ID = DCAMP.CAMPAIGN_SALESFORCE_ID
LEFT JOIN DM_ALUMNI.DIM_STRATEGY DSTRAT
ON DC.CONSTITUENT_PRIMARY_PROSPECT_STRATEGY_RECORD_ID = DSTRAT.STRATEGY_RECORD_ID
LEFT JOIN DM_ALUMNI.DIM_STRATEGY ODSTRAT
ON DCO.ORGANIZATION_PRIMARY_PROSPECT_STRATEGY_RECORD_ID = ODSTRAT.STRATEGY_RECORD_ID
-- Preferred addresses
LEFT JOIN assoc_dnr_count adr
  on adr.OPPORTUNITY_RECORD_ID = MKT.OPPORTUNITY_RECORD_ID
  AND adr.TX_ID = MKT.TX_ID
-- Preferred addresses
Left Join PREF_ADDRESS addr
  On addr.donor_ID = MKT.CREDITED_DONOR_ID
-- PRESIDENTIAL ADDRESS
LEFT JOIN PRES_ADDRESS PRESADDR
  ON PRESADDR.DONOR_ID = MKT.CREDITED_DONOR_ID
Left Join assoc_dnrs dnr2
  On dnr2.OPPORTUNITY_RECORD_ID = MKT.OPPORTUNITY_RECORD_ID
  And dnr2.DESIGNATION_NAME = MKT.DESIGNATION_NAME
  AND dnr2.TX_ID = MKT.TX_ID
--  AND dnr2.HARD_AND_SOFT_CREDIT_SALESFORCE_ID = MKT.HARD_AND_SOFT_CREDIT_SALESFORCE_ID
  And dnr2.attr_donor_rank = 2
--Associated donor 2  pref address
LEFT JOIN PREF_ADDRESS addrdnr2
  ON addrdnr2.donor_id = dnr2.CREDITED_DONOR_ID
--ASSOCIATED DONOR 2 DEGREE
Left Join ksm_deg ksm_deg2
  On ksm_deg2.donor_id = dnr2.CREDITED_DONOR_ID
-- ASSOCIATED DONOR 2 PRES ADDRESS
LEFT JOIN PRES_ADDRESS PRESDNR2
  ON PRESDNR2.DONOR_ID = dnr2.CREDITED_DONOR_ID
LEFT Join stg_alumni.ucinn_ascendv2__salutation__c  entitydnr2
  On entitydnr2.ucinn_ascendv2__contact__c = dnr2.SALESFORCE_ID
  AND entitydnr2.UCINN_ASCENDV2__SALUTATION_TYPE__C = 'Formal'
  AND entitydnr2.UCINN_ASCENDV2__SALUTATION_RECORD_TYPE_FORMULA__C = 'Ind'
LEFT Join stg_alumni.ucinn_ascendv2__salutation__c  jentitydnr2
  On jentitydnr2.ucinn_ascendv2__contact__c = dnr2.SALESFORCE_ID
  AND jentitydnr2.UCINN_ASCENDV2__SALUTATION_TYPE__C = 'Formal'
  AND jentitydnr2.UCINN_ASCENDV2__SALUTATION_RECORD_TYPE_FORMULA__C = 'Joint'
LEFT JOIN DM_ALUMNI.DIM_CONSTITUENT MEDNR2
ON MEDNR2.CONSTITUENT_DONOR_ID = DNR2.CREDITED_DONOR_ID
--another level of associated donor for when the primary donor is through foundation or DAF
Left Join assoc_dnrs dnr3
  On dnr3.OPPORTUNITY_RECORD_ID = MKT.OPPORTUNITY_RECORD_ID
  And dnr3.DESIGNATION_NAME = MKT.DESIGNATION_NAME
  AND dnr3.TX_ID = MKT.TX_ID
  And dnr3.attr_donor_rank = 3
--associated donor 3 pref address
LEFT JOIN PREF_ADDRESS addrdnr3
  ON addrdnr3.donor_id = dnr3.CREDITED_DONOR_ID
LEFT Join stg_alumni.ucinn_ascendv2__salutation__c  entitydnr3
  On entitydnr3.ucinn_ascendv2__contact__c = dnr3.SALESFORCE_ID
  AND entitydnr3.UCINN_ASCENDV2__SALUTATION_TYPE__C = 'Formal'
  AND entitydnr3.UCINN_ASCENDV2__SALUTATION_RECORD_TYPE_FORMULA__C = 'Ind'
LEFT JOIN DM_ALUMNI.DIM_CONSTITUENT MEDNR3
ON MEDNR3.CONSTITUENT_DONOR_ID = DNR3.CREDITED_DONOR_ID
Left Join ksm_deg ksm_deg3
  On ksm_deg3.donor_id = dnr3.CREDITED_DONOR_ID
-- Salutations
-- Joint gifts
Left Join joint_ind
  On joint_ind.OPPORTUNITY_RECORD_ID = MKT.OPPORTUNITY_RECORD_ID
  And joint_ind.HARD_AND_SOFT_CREDIT_SALESFORCE_ID = MKT.HARD_AND_SOFT_CREDIT_SALESFORCE_ID
Left Join ksm_deg
  On ksm_deg.donor_id = MKT.CREDITED_DONOR_ID
Left Join ksm_deg jksm_deg
  On jksm_deg.donor_id = ME.SPOUSE_DONOR_ID
-- Other gift attributes
Left Join first_gift
  On first_gift.CREDITED_DONOR_ID = MKT.CREDITED_DONOR_ID
WHERE MKT.CREDIT_TYPE = 'Hard'
  --AND MKT.CREDITED_DONOR_ID IN ('0000324229')
--0000414321', '0000678649')
 -- AND MKT.CREDIT_DATE >= KSM_PKG_UTILITY.to_date2('04052025', 'MMDDYYYY')
 -- AND MKT.CREDIT_DATE < KSM_PKG_UTILITY.to_date2('04082025', 'MMDDYYYY')
--AND MKT.CREDIT_DATE = KSM_PKG_UTILITY.to_date2('04082025', 'MMDDYYYY')
