CREATE OR REPLACE VIEW V_STEWARDSHIP_TOUCHPOINTS AS
with

dummy_years as (
select cal.CURR_FY - 1 as fy
from rpt_pbh634.v_current_calendar cal
union
select cal.curr_fy as fy
from rpt_pbh634.v_current_calendar cal
)

,MANUAL_DATES AS (
  SELECT
    *
  FROM RPT_PBH634.V_CURRENT_CALENDAR
)

,KSM_STAFF AS (
SELECT * FROM RPT_PBH634.V_FRONTLINE_KSM_STAFF
  WHERE FORMER_STAFF IS NULL
  AND TEAM IN ('AF', 'MG', 'ADV')
  AND ID_NUMBER NOT IN ('0000436760', '0000760399')
)

,pm_with_stop As (
Select
V.id_number
, V.report_name
, assignment_type_desc
, v.assignment_report_name
, v.start_dt_calc
, v.stop_dt_calc
, dy.fy
-- Dummy stop dt; fill in with arbitrary future year when assignment is active
, nvl(stop_dt_calc,
         Case When assignment_active_ind = 'Y' Then to_date(dy.FY || '0831', 'yyyymmdd') End)
  As dummy_stop_dt
-- Start and dummy stop FYs
--, rpt_pbh634.ksm_pkg_tmp.get_fiscal_year(START_DT_CALC)
--  As start_fy
, rpt_pbh634.ksm_pkg_tmp.get_fiscal_year(
     nvl(stop_dt_calc,
         Case When assignment_active_ind = 'Y' Then to_date(dy.FY || '0831', 'yyyymmdd') End)
  )
  As stop_fy
From rpt_pbh634.v_assignment_history v
Cross Join dummy_years dy
--INNER JOIN KSM_STAFF KST
--ON V.assignment_id_number = KST.ID_NUMBER
Where v.assignment_type = 'PM'
  --AND (V.start_dt_calc < cal.NEXT_FY_START
    -- AND NVL(V.STOP_DT_CALC, cal.NEXT_FY_START) > = cal.PREV_FY_START)
)

,PM_ASSIGNMENT AS (
  SELECT
ID_NUMBER
, REPORT_NAME
, ASSIGNMENT_TYPE_DESC
, STOP_FY
, MAX(ASSIGNMENT_REPORT_NAME) KEEP(DENSE_RANK FIRST ORDER BY DUMMY_STOP_DT DESC, START_DT_CALC DESC)
AS "PM_ON_8-31"
FROM pm_with_stop
WHERE STOP_FY >= FY
GROUP BY
ID_NUMBER
, REPORT_NAME
, ASSIGNMENT_TYPE_DESC
, STOP_FY
)


,lgo_with_stop As (
Select
V.id_number
, V.report_name
, assignment_type_desc
, v.assignment_report_name
, v.start_dt_calc
, v.stop_dt_calc
, dy.fy
-- Dummy stop dt; fill in with arbitrary future year when assignment is active
, nvl(stop_dt_calc,
         Case When assignment_active_ind = 'Y' Then to_date(dy.FY || '0831', 'yyyymmdd') End)
  As dummy_stop_dt
-- Start and dummy stop FYs
--, rpt_pbh634.ksm_pkg_tmp.get_fiscal_year(START_DT_CALC)
--  As start_fy
, rpt_pbh634.ksm_pkg_tmp.get_fiscal_year(
     nvl(stop_dt_calc,
         Case When assignment_active_ind = 'Y' Then to_date(dy.FY || '0831', 'yyyymmdd') End)
  )
  As stop_fy
From rpt_pbh634.v_assignment_history v
Cross Join dummy_years dy
INNER JOIN KSM_STAFF KST
ON V.assignment_id_number = KST.ID_NUMBER
Where v.assignment_type = 'LG'
 -- AND (V.start_dt_calc < cal.NEXT_FY_START
  --   AND NVL(V.STOP_DT_CALC, cal.NEXT_FY_START) > = cal.PREV_FY_START)
)

,LGO_ASSIGNMENT AS (
  SELECT
ID_NUMBER
, REPORT_NAME
, ASSIGNMENT_TYPE_DESC
, STOP_FY
, MAX(ASSIGNMENT_REPORT_NAME) KEEP(DENSE_RANK FIRST ORDER BY DUMMY_STOP_DT DESC, START_DT_CALC DESC)
AS "LGO_ON_8-31"
FROM lgo_with_stop
where STOP_FY >= FY
GROUP BY
ID_NUMBER
, REPORT_NAME
, ASSIGNMENT_TYPE_DESC
, STOP_FY
)

,STEWARDSHIP_CONTACT AS (
  SELECT
    C.id_number
    ,C.fiscal_year
    ,COUNT(C.report_id) AS STEWARDSHIP_CONTACT
  FROM RPT_PBH634.V_CONTACT_REPORTS_FAST C
  CROSS JOIN MANUAL_DATES MD
  INNER JOIN KSM_STAFF KST
  ON C.credited = KST.ID_NUMBER
  WHERE C.fiscal_year IN (MD.CURR_FY, MD.CURR_FY-1)
    AND KST.TEAM = 'ADV'
  GROUP BY C.ID_NUMBER, C.FISCAL_YEAR
)

,NOTE_ENTRIES AS (
SELECT
N.ID_NUMBER
,RPT_PBH634.KSM_PKG_TMP.get_fiscal_year(N.NOTE_DATE) AS FISCAL_YEAR
,COUNT(N.NOTE_ID) AS STEWARDSHIP_NOTES
FROM NOTES N
CROSS JOIN MANUAL_DATES MD
WHERE (N.NOTE_DATE >= MD.PREV_FY_START
   AND N.NOTE_TYPE IN ('AA', 'SG', 'SL', 'SP') AND N.AUTHOR_ID_NUMBER IN (SELECT ID_NUMBER FROM KSM_STAFF))
   OR (N.NOTE_DATE >= MD.PREV_FY_START
   AND N.NOTE_TYPE IN ('SG', 'SL', 'SP') AND N.AUTHOR_ID_NUMBER =  '0000804796')
GROUP BY N.ID_NUMBER, RPT_PBH634.KSM_PKG_TMP.get_fiscal_year(N.NOTE_DATE)
)

,TOP_PROSPECT AS (
SELECT DISTINCT
  ID_NUMBER
  ,'Y' AS "Top Campaign Prospect"
FROM PHILANTHROPIC_INTEREST
WHERE AFFINITY_PURPOSE_CODE = 'KG'
  AND AFFINITY_TYPE = 'EN'
  AND XCOMMENT = 'Top Campaign Prospect'
)

,DEAN_VISIT AS (
  SELECT DISTINCT
    C.id_number
    ,'Y' AS "DFC Visit"
  FROM RPT_PBH634.V_CONTACT_REPORTS_FAST C
    WHERE C.CONTACT_TYPE_CODE = 'V'
       AND C.credited = '0000804796'
)

,CAMPAIGN_EVENT AS (
  SELECT DISTINCT
    C.ID_NUMBER
    ,'Y' AS "Campaign Event"
  FROM RPT_PBH634.V_CONTACT_REPORTS_FAST C
    WHERE C.CONTACT_TYPE_CODE = 'N'
      AND C.credited = '0000804796'
       AND (C.description LIKE '%Campaign%' OR C.description LIKE '%campaign%')
)

,LIAISON_ASSIGNMENT As (
Select
V.id_number
,v.assignment_report_name
From rpt_pbh634.v_assignment_history v
Where v.assignment_type = 'PO'
  AND V.assignment_active_ind = 'Y'
  AND V.ASSIGNMENT_ID_NUMBER = '0000804796'
)


,ALL_ENTITIES AS (
SELECT
  ID_NUMBER
  ,2025 AS FISCAL_YEAR
FROM TOP_PROSPECT TP
UNION
SELECT
  ID_NUMBER
  ,2025 AS FISCAL_YEAR
FROM DEAN_VISIT DV
UNION
SELECT
  ID_NUMBER
  ,2025 AS FISCAL_YEAR
FROM CAMPAIGN_EVENT CE
UNION
SELECT
  ID_NUMBER
  ,2025 AS FISCAL_YEAR
FROM LIAISON_ASSIGNMENT LA
UNION
SELECT
  ID_NUMBER
  ,PM.STOP_FY AS FISCAL_YEAR
FROM PM_ASSIGNMENT PM
UNION
SELECT
  ID_NUMBER
  ,LA.STOP_FY AS FISCAL_YEAR
FROM LGO_ASSIGNMENT LA
UNION
SELECT
  ID_NUMBER
  ,SC.FISCAL_YEAR
FROM STEWARDSHIP_CONTACT SC
UNION
SELECT
   ID_NUMBER
  ,NE.FISCAL_YEAR
FROM NOTE_ENTRIES NE
UNION
SELECT DISTINCT
    A.ID_NUMBER
  ,RPT_PBH634.KSM_PKG_TMP.to_number2(A.APPEAL_YEAR) AS FISCAL_YEAR
FROM APPEALS A
INNER JOIN APPEAL_HEADER AH
ON A.APPEAL_CODE = AH.APPEAL_CODE
WHERE AH.DESCRIPTION LIKE '%KLC Welcome%'
UNION
SELECT DISTINCT
    EV.id_number
  ,EV.start_fy_calc AS FISCAL_YEAR
FROM RPT_PBH634.V_NU_EVENT_PARTICIPANTS_FAST EV
INNER JOIN EP_EVENT_ORGANIZER EO
ON EV.event_id = EO.EVENT_ID
WHERE EO.NOTE = 'KLC'
)

,APPEAL_INFO AS (
SELECT
  A.ID_NUMBER
  ,RPT_PBH634.KSM_PKG_TMP.to_number2(A.APPEAL_YEAR) AS APPEAL_YEAR
  ,COUNT(DISTINCT A.ID_NUMBER) AS TOTAL_APPEALS
FROM APPEALS A
INNER JOIN ALL_ENTITIES AE
ON A.ID_NUMBER = AE.ID_NUMBER
INNER JOIN APPEAL_HEADER AH
ON A.APPEAL_CODE = AH.APPEAL_CODE
WHERE AH.DESCRIPTION LIKE '%KLC Welcome%'
GROUP BY A.ID_NUMBER, A.APPEAL_YEAR
)

,EVENT_INFO AS (
SELECT
  EP.ID_NUMBER
  ,EP.start_fy_calc
  ,COUNT (DISTINCT EP.event_id) AS TOTAL_EVENT_INVITES
  ,COUNT (DISTINCT (CASE WHEN EP.participated_flag = 'Y' THEN EP.EVENT_ID END)) AS TOTAL_EVENTS_ATTENDED
FROM RPT_PBH634.V_NU_EVENT_REGISTRANTS EP
--RPT_PBH634.V_NU_EVENT_PARTICIPANTS_FAST EP
INNER JOIN ALL_ENTITIES AE
ON EP.ID_NUMBER = AE.ID_NUMBER
INNER JOIN EP_EVENT_ORGANIZER EO
ON EP.event_id = EO.EVENT_ID
WHERE EO.NOTE = 'KLC'
GROUP BY EP.ID_NUMBER, EP.start_fy_calc
)

,KLC AS (
SELECT * FROM TABLE(RPT_ABM1914.KSM_PKG_KLC.tbl_klc_members_range(2017, 2025))
WHERE KLC_LEV_CFY <> ' '
)

SELECT DISTINCT
  KH.ID_NUMBER
  ,KH.HOUSEHOLD_NAME
  ,KH.INSTITUTIONAL_SUFFIX
  ,KH.HOUSEHOLD_ID
  ,KH.HOUSEHOLD_PRIMARY
  ,KH.RECORD_STATUS_CODE
  ,KH.SPOUSE_ID_NUMBER
  ,KH.HOUSEHOLD_SPOUSE
  ,KH.SPOUSE_SUFFIX
  ,AE.FISCAL_YEAR
  ,PM."PM_ON_8-31"
  ,PKST.ID_NUMBER AS "PM ID_NUMBER"
  ,PKST.TEAM AS "PM TEAM"
  ,LA."LGO_ON_8-31"
  ,LKST.ID_NUMBER AS "LGO ID_NUMBER"
  ,LKST.TEAM AS "LGO TEAM"
  ,SC.STEWARDSHIP_CONTACT
  ,NE.STEWARDSHIP_NOTES
  ,AI.TOTAL_APPEALS
  ,EI.TOTAL_EVENTS_ATTENDED
  ,CASE WHEN KLC.ID_NUMBER IS NOT NULL THEN 'Y' ELSE ' ' END AS KLC
  ,TP."Top Campaign Prospect"
  ,CE."Campaign Event"
  ,DV."DFC Visit"
  ,CASE WHEN LA.assignment_report_name = 'Cornelli PhD, Francesca' THEN 'Y' END AS "University Liaison"
FROM RPT_PBH634.V_ENTITY_KSM_HOUSEHOLDS_FAST KH
INNER JOIN ALL_ENTITIES AE
ON KH.ID_NUMBER = AE.ID_NUMBER
LEFT JOIN PM_ASSIGNMENT PM
ON AE.ID_NUMBER = PM.ID_NUMBER
  AND AE.FISCAL_YEAR = PM.STOP_FY
LEFT JOIN KSM_STAFF PKST
ON PM."PM_ON_8-31" = PKST.REPORT_NAME
LEFT JOIN LGO_ASSIGNMENT LA
ON AE.ID_NUMBER = LA.ID_NUMBER
  AND AE.FISCAL_YEAR = LA.STOP_FY
LEFT JOIN KSM_STAFF LKST
ON LA."LGO_ON_8-31" = LKST.REPORT_NAME
LEFT JOIN STEWARDSHIP_CONTACT SC
ON AE.ID_NUMBER = SC.ID_NUMBER
  AND AE.FISCAL_YEAR = SC.FISCAL_YEAR
LEFT JOIN NOTE_ENTRIES NE
ON AE.ID_NUMBER = NE.ID_NUMBER
  AND AE.FISCAL_YEAR = NE.FISCAL_YEAR
LEFT JOIN APPEAL_INFO AI
ON AE.ID_NUMBER = AI.ID_NUMBER
  AND AE.FISCAL_YEAR = AI.APPEAL_YEAR
LEFT JOIN EVENT_INFO EI
ON AE.ID_NUMBER = EI.ID_NUMBER
  AND AE.FISCAL_YEAR = EI.start_fy_calc
LEFT JOIN KLC
ON AE.ID_NUMBER = KLC.ID_NUMBER
  AND AE.FISCAL_YEAR = KLC.FISCAL_YR
LEFT JOIN TOP_PROSPECT TP
ON AE.ID_NUMBER = TP.ID_NUMBER
 -- AND AE.FISCAL_YEAR = TP.FISCAL_YEAR
LEFT JOIN DEAN_VISIT DV
ON AE.ID_NUMBER = DV.ID_NUMBER
 -- AND AE.FISCAL_YEAR = DV.FISCAL_YEAR
LEFT JOIN CAMPAIGN_EVENT CE
ON AE.ID_NUMBER = CE.ID_NUMBER
  --AND AE.FISCAL_YEAR = CE.FISCAL_YEAR
LEFT JOIN LIAISON_ASSIGNMENT LA
ON AE.ID_NUMBER = LA.ID_NUMBER
  --AND AE.FISCAL_YEAR = LA.STOP_FY
ORDER BY KH.HOUSEHOLD_NAME, AE.FISCAL_YEAR ASC
;
